name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: read-all

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest]
        rust: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - name: Update Rust
        run: rustup update

      - name: Install targets
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - name: Build x86_64
        run: |
          cargo rustc --release --target x86_64-apple-darwin 

      - name: Build arm64
        run: |
          cargo rustc --release --target aarch64-apple-darwin

      - name: Run Clippy
        run: cargo clippy --all

      - name: Run tests
        run: cargo test --all

